Saeed99Madi/MSS-E-Commarce

client/src/components/dashboard/Products/AddProduct/TextInput.tsx, client/src/components/dashboard/Products/AddProduct/components.styled.tsx, client/src/components/dashboard/Products/AddProduct/index.tsx, client/src/components/dashboard/Services/AddService/TextInput.tsx, client/src/components/dashboard/Services/AddService/components.styled.tsx, client/src/components/dashboard/SettingsManage/TextInput/index.tsx
=> fix dashboard forms styling

client/src/components/dashboard/Login/index.tsx, client/src/components/dashboard/NavBar/index.tsx, client/src/context/AuthContext.tsx, client/src/pages/dashboard.tsx, client/src/routes/index.tsx
=> fix Authenmtication Bug

client/pages/index.tsx
=> remove the console log

README.md
=> add next and there tecknologies in readme file

client/components/Home/ServicesList/components.styled.tsx, client/package-lock.json, client/package.json
=> 100 services section

client/components/Home/ServicesList/components.styled.tsx
=> make services section responsive

client/components/Home/ServicesList/components.styled.tsx
=> make transition for responsive

client/components/Home/TopCategories/components.styled.tsx, client/components/Home/TopCategories/index.tsx, client/pages/index.tsx
=> 105 top categories

dashboard/src/components/dashboard/Categories/CategoriesList/component.style.tsx
=> fix spacing in category page

client/components/Home/HeadSection/components.styled.tsx, client/components/Home/HeadSection/index.tsx
=> 109 responsive lead section

client/components/Footer/components.styled.tsx, client/components/Footer/index.tsx, client/components/Home/ContactSection/components.styled.tsx, client/components/Home/FeaturedProducts/components.styled.tsx, client/components/Home/TopCategories/components.styled.tsx
=> Responsive Footer

dashboard/src/components/dashboard/Actions/MarkAs/index.tsx
=> fix Bug publish and unpublish

client/components/Product/ProductFeatures/index.tsx, client/components/Product/ProductName/ProductDetails.tsx, client/components/Product/ProductName/ProductImages.tsx, client/components/Product/ProductName/index.tsx, client/components/Product/RelatedProducts/index.tsx, client/components/Product/components.styled.tsx, client/pages/index.tsx, client/pages/product/index.tsx, client/utils/devices/index.ts, src/controllers/CategoriesController.ts
related to #125
- laptop
- mobile
> ![Screenshot from 2023-01-22 14-21-42](https://user-images.githubusercontent.com/67611935/213915554-2968e99c-b31d-4442-aa39-97855aea8652.png)
> 
> 
> ![Screenshot from 2023-01-22 14-20-54](https://user-images.githubusercontent.com/67611935/213915490-0f228241-b064-4b1c-8266-1f7d9f3e1243.png)
>
=> create product name section

dashboard/src/App.css, dashboard/src/components/dashboard/Actions/MarkAs/index.tsx, dashboard/src/components/dashboard/Products/Card/index.tsx, dashboard/src/components/dashboard/Products/index.tsx, dashboard/src/components/dashboard/components.styled.tsx
=> solve Scrolling Bug in Dashboard

dashboard/src/App.css
=> fix dashboard scroll issue

client/components/Product/RelatedProducts/ProductCard.tsx, client/components/Product/RelatedProducts/index.tsx, client/components/Product/components.styled.tsx
related to #127
- laptop
- mobile
=> create related product section

src/controllers/ProductController.ts, src/db/connection.ts, src/models/Product.ts, src/routes/products.ts
=> 138 edit product route

dashboard/src/components/dashboard/Products/AddProduct/AttriputeForms/AttriputeCard/index.tsx, dashboard/src/components/dashboard/Products/AddProduct/AttriputeForms/index.tsx, dashboard/src/components/dashboard/Products/AddProduct/UploadProductFiles/index.tsx, dashboard/src/components/dashboard/Products/EditProduct/UploadProductFiles/index.tsx, dashboard/src/components/dashboard/Products/EditProduct/index.tsx, dashboard/src/interfaces/IProduct.ts
=> 139 modify edit product

dashboard/src/components/dashboard/Actions/Search/index.tsx, dashboard/src/components/dashboard/Categories/AddCategories/index.tsx, dashboard/src/components/dashboard/Categories/CategoriesList/ListItem.tsx, dashboard/src/components/dashboard/Categories/CategoriesList/component.style.tsx, dashboard/src/components/dashboard/Categories/CategoriesList/index.tsx, dashboard/src/components/dashboard/Categories/UpdateCategory/index.tsx, dashboard/src/components/dashboard/Categories/component.styled.tsx, dashboard/src/components/dashboard/Login/index.tsx, dashboard/src/components/dashboard/Products/AddProduct/AttriputeForms/AttriputeCard/index.tsx, dashboard/src/components/dashboard/Products/AddProduct/UploadProductFiles/index.tsx, dashboard/src/components/dashboard/Products/AddProduct/index.tsx, dashboard/src/components/dashboard/Products/Card/index.tsx, dashboard/src/components/dashboard/Products/EditProduct/UploadProductFiles/index.tsx, dashboard/src/components/dashboard/Products/EditProduct/index.tsx, dashboard/src/context/AuthContext.tsx, dashboard/src/helpers/AttriputeReducer.ts, dashboard/src/pages/dashboard.tsx
=> lintier all files and handle success and failed status

dashboard/src/components/dashboard/Actions/MarkAs/index.tsx, dashboard/src/components/dashboard/ConfermAction/index.tsx, dashboard/src/components/dashboard/Products/AddProduct/index.tsx, dashboard/src/components/dashboard/Products/Card/index.tsx, dashboard/src/components/dashboard/Products/EditProduct/index.tsx, dashboard/src/context/DashboardContext.tsx, dashboard/src/interfaces/IDashboardContext.ts, dashboard/src/pages/dashboard.tsx, src/controllers/ProductController.ts
=> 142 full check products components

dashboard/src/components/dashboard/Services/Actions/MarkAs/index.tsx, dashboard/src/components/dashboard/Services/Card/index.tsx, dashboard/src/components/dashboard/Services/EditService/UploadServiceFiles/index.tsx, dashboard/src/components/dashboard/Services/EditService/index.tsx, dashboard/src/components/dashboard/Services/index.tsx, dashboard/src/context/DashboardContext.tsx, dashboard/src/interfaces/IDashboardContext.ts, dashboard/src/interfaces/IService.ts
=> 146 improve services management "Dashboard"

src/controllers/ServicesController.ts, src/routes/services.ts
=> create update Services Route

client/components/Footer/components.styled.tsx, client/components/Header/components.styled.tsx, client/components/Home/ContactSection/components.styled.tsx, client/components/Home/FeaturedProducts/index.tsx, client/components/Home/ServicesList/components.styled.tsx, client/components/Home/ServicesList/index.tsx, client/components/Home/TopCategories/components.styled.tsx, client/components/Home/TopCategories/index.tsx
=> 157 fix home styles

client/components/ContactSaid/components.styled.tsx, client/components/ContactSaid/index.tsx, client/components/Product/ProductName/ProductImages.tsx, client/components/Product/RelatedProducts/Arrows.tsx, client/components/Product/RelatedProducts/ProductCard.tsx, client/components/Product/RelatedProducts/index.tsx, client/components/Product/components.styled.tsx, client/package-lock.json, client/package.json, client/pages/contacts/index.tsx
=> 164 modify product section

src/controllers/ProductController.ts, src/routes/products.ts
=> 160 get published products

src/controllers/ProductController.ts, src/routes/products.ts
=> create api to get product details
